import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/Navbar";
// import React, { useEffect, useState } from 'react';
import ShowNavbarWrapper from '@/components/ShowNavbarWrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [showNavbar, setShowNavbar] = useState(false);

  // useEffect(() => {
  //   if (typeof window !== 'undefined') {
  //     const role = localStorage.getItem('role');
  //     setShowNavbar(!!role);
  //   }
  // }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ShowNavbarWrapper />
        <div id="main-content" >
          {children}
        </div>
      </body>
    </html>
  );
}
