services:
  account-service:
    build: ./account-service
    ports:
      - "8001:8001"
    volumes:
      - ./account-service/app:/app/app
      - ./account-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./account-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  post-service:
    build: ./post-service
    ports:
      - "8002:8002"
    volumes:
      - ./post-service/app:/app/app
      - ./post-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./post-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  chatbot-service:
    build: ./chatbot-service
    ports:
      - "8003:8003"
    volumes:
      - ./chatbot-service/app:/app/app
      - ./chatbot-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./chatbot-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  contract-service:
    build: ./contract-service
    ports:
      - "8004:8004"
    volumes:
      - ./contract-service/app:/app/app
      - ./contract-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./contract-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  finance-service:
    build: ./finance-service
    ports:
      - "8005:8005"
    volumes:
      - ./finance-service/app:/app/app
      - ./finance-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./finance-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "8006:8006"
    volumes:
      - ./product-service/app:/app/app
      - ./product-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./product-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - app-network

  organization-service:
    build: ./organization-service
    ports:
      - "8007:8007"
    volumes:
      - ./organization-service/app:/app/app
      - ./organization-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./organization-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - app-network

  gateway:
    build: ./gateway
    ports:
      - "8090:8080"
    volumes:
      - ./gateway:/app
    env_file:
      - ./gateway/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    depends_on:
      - account-service
      - post-service
      - chatbot-service
      - contract-service
      - finance-service
      - product-service
      - organization-service
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://gateway:8080/api/v1
    depends_on:
      - gateway
    networks:
      - app-network

networks:
  app-network:
    driver: bridge